import Link from "next/link";
import { Nav } from "@/components/nav";
import { ExportBusiness } from "@/components/export-business";
import { requireSession } from "@/lib/auth";
import { rows } from "@/lib/db";
import { businessPeriod,businessSummary,costChanges,costLabels,COST_GROUPS,dueBucket,type BusinessLine,type CostGroup } from "@/lib/business";
import { monthEnd,monthOffset } from "@/lib/household";
import { analyticsMoney as money } from "@/lib/analytics";
import "./business.css";
export const dynamic="force-dynamic";
type Targets={revenue:number|null;expenses:number|null;profit:number|null};
export default async function BusinessPage({searchParams}:{searchParams:Promise<{month?:string;saved?:string;error?:string}>}){
  const viewer=await requireSession();const params=await searchParams;
  const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Colombo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  const period=businessPeriod(params.month||today.slice(0,7),today);
  if(!period)return <><Nav/><main><h1>Business</h1><p role="alert">Choose a valid reporting month up to the current month.</p><Link href="/business">Current month</Link></main></>;
  const {month,start,end,previousStart,previousEnd,trendStart}=period;
  const [activity,settings,categories,cashRows,receivables,payables,pendingRows]=await Promise.all([
    rows<any>(`SELECT t.id,t.activityId,t.transactionDate,t.type,t.status,t.owner,t.scope,t.amount,t.categoryId,COALESCE(c.name,'Uncategorized') category,t.projectId,COALESCE(p.name,'General business / no project') project
      FROM IncomeExpenseActivity t LEFT JOIN Category c ON c.id=t.categoryId LEFT JOIN Project p ON p.id=t.projectId
      WHERE t.scope='BUSINESS' AND t.status='POSTED' AND t.type IN ('INCOME','EXPENSE','ACCRUED_EXPENSE') AND t.transactionDate>=? AND t.transactionDate<=?`,[trendStart,end]),
    rows<any>("SELECT `key`,value FROM AppSetting WHERE `key` LIKE 'businessCost:%' OR `key`=?",[`businessTargets:${month}`]),
    rows<any>("SELECT id,name FROM Category WHERE kind='EXPENSE' ORDER BY name"),
    rows<any>(`SELECT COALESCE(SUM(CASE WHEN e.amount>0 THEN e.amount ELSE 0 END),0) receipts,COALESCE(SUM(CASE WHEN e.amount<0 THEN -e.amount ELSE 0 END),0) payments
      FROM AccountEntry e JOIN Account a ON a.id=e.accountId JOIN FinancialTransaction t ON t.id=e.transactionId
      WHERE a.type IN ('CASH','BANK','SAVINGS') AND t.scope='BUSINESS' AND t.status='POSTED' AND t.type IN ('INCOME','EXPENSE','PARTY_PAYMENT') AND e.entryDate>=? AND e.entryDate<=?`,[start,end]),
    rows<any>("SELECT o.id,o.partyId,t.description,t.dueDate,p.name, o.balance amount FROM CreditOutstanding o JOIN FinancialTransaction t ON t.id=o.id LEFT JOIN Party p ON p.id=o.partyId WHERE o.scope='BUSINESS' AND o.type='INCOME' AND o.balance>0.005 ORDER BY t.dueDate,o.id"),
    rows<any>("SELECT t.id,t.partyId,a.description,a.dueDate,COALESCE(p.name,t.counterparty,'Unlinked supplier') name,GREATEST(a.amount-a.paidAmount,0) amount FROM AccruedExpense a JOIN FinancialTransaction t ON t.accrualId=a.id LEFT JOIN Party p ON p.id=t.partyId WHERE t.scope='BUSINESS' AND t.status='POSTED' AND a.status IN ('OPEN','PARTIALLY_PAID') AND a.amount>a.paidAmount ORDER BY a.dueDate,t.id"),
    rows<any>("SELECT COUNT(*) count FROM FinancialTransaction WHERE status='PENDING_REVIEW'")
  ]);
  const costs:Record<string,CostGroup>={};let targets:Targets={revenue:null,expenses:null,profit:null};
  for(const s of settings){try{const v=JSON.parse(s.value);if(s.key.startsWith("businessCost:")&&COST_GROUPS.includes(v))costs[s.key.slice(13)]=v;
    if(s.key===`businessTargets:${month}`&&v&&["revenue","expenses","profit"].every(k=>v[k]===null||(Number.isFinite(v[k])&&v[k]>=0)))targets=v;
  }catch{/* Invalid optional settings remain unset. */}}
  const lines=activity as BusinessLine[],current=businessSummary(lines,start,end,costs,viewer),previous=businessSummary(lines,previousStart,previousEnd,costs,viewer);
  const months=Array.from({length:6},(_,i)=>monthOffset(month,i-5)).map(m=>({month:m,...businessSummary(lines,`${m}-01`,m===month?end:monthEnd(m),costs,viewer)}));
  const changes=costChanges(current,previous),receipts=Number(cashRows[0]?.receipts??0),payments=Number(cashRows[0]?.payments??0);
  const sum=(items:any[])=>items.reduce((s,i)=>s+Math.round(Number(i.amount)*100),0)/100;
  const overdue=(items:any[])=>items.filter(i=>i.dueDate&&String(i.dueDate).slice(0,10)<today);
  const owed=sum(receivables),owing=sum(payables),overdueIn=sum(overdue(receivables)),overdueOut=sum(overdue(payables));
  const profitChange=Math.round((current.profit-previous.profit)*100)/100,maxTrend=Math.max(1,...months.flatMap(m=>[m.revenue,m.expenses]));
  const targetRows=[{key:"revenue",label:"Revenue target",target:targets.revenue,actual:current.revenue},{key:"expenses",label:"Expense ceiling",target:targets.expenses,actual:current.expenses},{key:"profit",label:"Profit target",target:targets.profit,actual:current.profit}];
  const csv:(string|number)[][]=[["Business management report",`${start} to ${end}`],["Basis","Actual Business labels; posted records; income and recorded expenses including credit sales and unpaid bills."],["Measure","LKR"],["Revenue",current.revenue],["Direct costs",current.groups.DIRECT],["Operating overhead",current.groups.OVERHEAD],["Finance costs",current.groups.FINANCE],["Tax expense",current.groups.TAX],["Unclassified costs",current.groups.UNCLASSIFIED],["Recorded net profit",current.profit],["Net margin (%)",current.margin??"N/A"],["Trading cash receipts",receipts],["Trading cash payments",payments],[],["Project","Revenue","Assigned costs","Result before unallocated shared costs"],...current.projects.map(p=>[p.name,p.revenue,p.cost,p.result]),[],["Expense category","Cost group","Amount"],...current.categories.map(c=>[c.name,costLabels[c.group],c.amount])];
  return <><Nav/><main className="business-page">
    <div className="page-heading"><div><p className="eyebrow">Profit · Costs · Collections</p><h1>Business</h1></div><div className="hh-actions"><ExportBusiness data={csv} month={month}/><Link className="button primary" href="/transactions/new?scope=BUSINESS">Add transaction</Link></div></div>
    <form className="business-period"><label>Reporting month<input type="month" name="month" defaultValue={month} max={today.slice(0,7)} min="1900-01" required/></label><button className="button">View</button><Link href="/business">This month</Link><span>{start} to {end}{period.current?" · Month to date":" · Full month"}</span></form>
    {params.saved&&<p role="status">Business settings saved.</p>}{params.error&&<p role="alert">Unable to save. Check the category and target amounts.</p>}
    <section className="metric-grid" aria-label="Business performance">
      <article className="metric"><p>Revenue</p><strong>{money(current.revenue)}</strong><small>Includes recorded credit sales</small></article>
      <article className="metric"><p>Total costs</p><strong>{money(current.expenses)}</strong><small>Paid expenses + unpaid bills</small></article>
      <article className={`metric ${current.profit>=0?"positive":"negative"}`}><p>Recorded net profit</p><strong>{money(current.profit)}</strong><small className={profitChange>=0?"balance-positive":"balance-negative"}>{money(profitChange)} vs previous period</small></article>
      <article className="metric"><p>Net profit margin</p><strong>{current.margin===null?"—":`${current.margin.toFixed(1)}%`}</strong><small>Profit ÷ revenue · {current.count} transactions</small></article>
    </section>
    <p className="business-note">Comparison: {previousStart} to {previousEnd}. Personal, wife, pending, void, transfers and principal payments are excluded from profit. Tax labels do not change this dashboard.</p>
    {!current.count&&<div className="panel"><p>No posted business income or expenses in this period.</p><Link href="/transactions/new?scope=BUSINESS">Record a business transaction</Link></div>}
    <div className="business-grid">
      <section className="panel"><div className="section-heading"><h2>Profit & loss</h2><a href="#cost-control">Classify costs</a></div><dl className="business-statement"><div><dt>Revenue</dt><dd>{money(current.revenue)}</dd></div><div><dt>Less: direct costs</dt><dd>{money(current.groups.DIRECT)}</dd></div><div className="subtotal"><dt>Gross profit</dt><dd>{current.grossProfit===null?"Classify costs first":money(current.grossProfit)}</dd></div><div><dt>Less: operating overhead</dt><dd>{money(current.groups.OVERHEAD)}</dd></div><div className="subtotal"><dt>Operating profit</dt><dd>{current.operatingProfit===null?"—":money(current.operatingProfit)}</dd></div><div><dt>Less: finance costs</dt><dd>{money(current.groups.FINANCE)}</dd></div><div><dt>Profit before recorded tax</dt><dd>{current.beforeTax===null?"—":money(current.beforeTax)}</dd></div><div><dt>Less: tax expenses recorded</dt><dd>{money(current.groups.TAX)}</dd></div>{current.groups.UNCLASSIFIED>0&&<div><dt>Less: unclassified costs</dt><dd>{money(current.groups.UNCLASSIFIED)}</dd></div>}<div className="subtotal"><dt>Recorded net profit</dt><dd>{money(current.profit)}</dd></div></dl><p className="business-note">Gross and operating profit appear once all period costs are classified. Net profit includes every recorded cost. Inventory usage, depreciation, interest and tax are included only when recorded as expenses.</p></section>
      <section className="panel"><h2>Six-month performance</h2><p className="business-note">Revenue <span className="business-legend revenue">●</span> · Costs <span className="business-legend costs">●</span>{period.current?" · Latest month is partial":""}</p><div className="business-trends">{months.map(m=><div key={m.month}><div className="business-trend-label"><strong>{m.month}</strong><span className={m.profit<0?"business-loss":""}>Profit {money(m.profit)}</span></div><progress aria-label={`${m.month} revenue ${money(m.revenue)}`} value={m.revenue} max={maxTrend}/><progress className="costs" aria-label={`${m.month} costs ${money(m.expenses)}`} value={m.expenses} max={maxTrend}/></div>)}</div><details><summary>View exact values</summary>{months.map(m=><p key={m.month}>{m.month}: revenue {money(m.revenue)} · costs {money(m.expenses)} · profit {money(m.profit)}</p>)}</details></section>
      <section className="panel"><h2>Management priorities</h2><ul className="business-priorities">
        {current.profit<0&&<li><strong>Period loss: {money(-current.profit)}</strong><span>Review the largest costs and projects with negative results below.</span></li>}
        {current.groups.UNCLASSIFIED>0&&<li><a href="#cost-control">Classify {money(current.groups.UNCLASSIFIED)} of costs</a><span>This is needed for gross and operating profit.</span></li>}
        {overdueIn>0&&<li><a href="#credit">Follow up {money(overdueIn)} overdue from customers</a></li>}
        {overdueOut>0&&<li><a href="#credit">Review {money(overdueOut)} overdue to suppliers</a></li>}
        {changes.slice(0,3).map(c=><li key={c.id}><strong>{c.name}: +{money(c.increase)}</strong><span>Cost increase against the comparison period{c.previous===0?" (no previous spending)":""}.</span></li>)}
        {Number(pendingRows[0]?.count)>0&&<li><Link href="/review">Complete {pendingRows[0].count} draft entries</Link><span>All your drafts; their business/personal labels may still be incomplete.</span></li>}
      </ul>{current.profit>=0&&!current.groups.UNCLASSIFIED&&!overdueIn&&!overdueOut&&!changes.length&&!Number(pendingRows[0]?.count)&&<p>No cost increases, losses, overdue balances or pending entries detected in the recorded data.</p>}</section>
      <section className="panel"><h2>Cash from business activity</h2><dl className="business-statement"><div><dt>Cash received</dt><dd>{money(receipts)}</dd></div><div><dt>Cash paid</dt><dd>{money(payments)}</dd></div><div className="subtotal"><dt>Net trading cash movement</dt><dd>{money(Math.round((receipts-payments)*100)/100)}</dd></div></dl><p className="business-note">Selected-period receipts and payments through cash, bank and savings accounts, including credit settlements. Unpaid sales/bills and credit-card purchases do not move cash. Account transfers and card/loan principal payments are excluded.</p><Link href={`/analytics?scope=BUSINESS&start=${start}&end=${end}`}>Explore business transactions</Link></section>
    </div>
    <section className="panel" id="projects"><h2>Project performance</h2><p className="business-note">Revenue less costs assigned to each project. Shared costs stay in General business; they are not automatically allocated to projects. These results are before any unallocated shared costs.</p><div className="table-wrap"><table><thead><tr><th>Project</th><th>Revenue</th><th>Assigned costs</th><th>Result</th><th>Margin</th></tr></thead><tbody>{current.projects.map(p=><tr key={p.id}><td>{p.id?<Link href={`/analytics?scope=BUSINESS&start=${start}&end=${end}&projectId=${encodeURIComponent(p.id)}`}>{p.name}</Link>:p.name}</td><td>{money(p.revenue)}</td><td>{money(p.cost)}</td><td className={p.result<0?"business-loss":""}>{money(p.result)}</td><td>{p.margin===null?"—":`${p.margin.toFixed(1)}%`}</td></tr>)}{!current.projects.length&&<tr><td colSpan={5}>No project activity in this period.</td></tr>}</tbody></table></div></section>
    <div className="business-grid">
      <section className="panel" id="cost-control"><h2>Cost control</h2><div className="business-costs">{current.categories.slice(0,8).map(c=><div key={c.id}><div><strong>{c.name}</strong><span>{money(c.amount)} · {c.share.toFixed(1)}%</span></div><progress aria-label={`${c.name}: ${c.share.toFixed(1)}% of costs`} max={100} value={c.share}/><small>{costLabels[c.group]}</small></div>)}{!current.categories.length&&<p>No expenses in this period.</p>}</div><details><summary>Manage cost groups / all categories</summary><p className="business-note">Direct costs are attributable to delivering your work; overhead supports the business generally. Assign categories to suit your records. Changes apply across all reporting periods.</p>{[...categories,{id:"uncategorized",name:"Uncategorized"}].map(c=><form className="business-cost-form" action="/api/business" method="post" key={c.id}><input type="hidden" name="intent" value="cost"/><input type="hidden" name="month" value={month}/><input type="hidden" name="categoryId" value={c.id}/><label>{c.name}<select name="costGroup" defaultValue={costs[c.id]||"UNCLASSIFIED"}>{COST_GROUPS.map(g=><option key={g} value={g}>{costLabels[g]}</option>)}</select></label><button className="button">Save</button></form>)}</details></section>
      <section className="panel"><h2>Monthly targets</h2><p className="business-note">{month} full-month targets against {period.current?"month-to-date":"full-month"} results. Blank means no target; zero is a valid target.</p>{targetRows.map(r=><div className="business-target" key={r.key}><div><strong>{r.label}</strong><span>{r.target===null?"Not set":`${money(r.actual)} / ${money(r.target)}`}</span></div>{r.target!==null&&<><progress aria-label={r.label} value={Math.max(0,Math.min(r.actual,r.target||1))} max={r.target||1}/><small>{r.key==="expenses"?(r.actual>r.target?`${money(r.actual-r.target)} over ceiling`:`${money(r.target-r.actual)} remaining`):(r.actual>=r.target?"Target achieved":`${money(r.target-r.actual)} to target`)}</small></>}</div>)}<details><summary>Edit monthly targets</summary><form className="form-grid" action="/api/business" method="post"><input type="hidden" name="intent" value="targets"/><input type="hidden" name="month" value={month}/>{targetRows.map(r=><label key={r.key}>{r.label}<input type="number" name={r.key} min="0" max="999999999" step="0.01" defaultValue={r.target??""} placeholder="Not set"/></label>)}<button className="button primary">Save targets</button></form></details></section>
    </div>
    <section className="panel" id="credit"><div className="section-heading"><div><h2>Customer & supplier balances</h2><p className="business-note">Latest recorded balances across all dates, independent of the reporting month. Overdue status uses {today}.</p></div><Link href="/master-data/parties">Manage contacts</Link></div><div className="business-credit-totals"><div><span>Customers owe you</span><strong>{money(owed)}</strong><small>{money(overdueIn)} overdue</small></div><div><span>You owe suppliers</span><strong>{money(owing)}</strong><small>{money(overdueOut)} overdue</small></div></div><div className="table-wrap"><table><thead><tr><th>Customer / supplier</th><th>Transaction</th><th>Receive</th><th>Pay</th><th>Due date</th><th>Status</th></tr></thead><tbody>{[...receivables.map(r=>({...r,side:"receive"})),...payables.map(r=>({...r,side:"pay"}))].map(r=><tr key={`${r.side}:${r.id}`}><td>{r.partyId?<Link href={`/parties/${r.partyId}`}>{r.name}</Link>:r.name||"Unlinked contact"}</td><td>{r.description||"Credit transaction"}</td><td>{r.side==="receive"?money(r.amount):"—"}</td><td>{r.side==="pay"?money(r.amount):"—"}</td><td>{r.dueDate?String(r.dueDate).slice(0,10):"Not set"}</td><td>{dueBucket(r.dueDate?String(r.dueDate).slice(0,10):null,today)}{r.side==="pay"&&<small><Link href={`/bills?bill=${r.id}#payment`}>Pay bill</Link></small>}</td></tr>)}{!receivables.length&&!payables.length&&<tr><td colSpan={6}>No outstanding recorded business credit balances.</td></tr>}</tbody></table></div></section>
  </main></>;
}
