import Link from "next/link";
import { Nav } from "@/components/nav";
import { requireSession } from "@/lib/auth";
import { cashRows, familyPaymentAccounts } from "@/lib/db";
import { dateValue, lkr } from "@/lib/format";

type Account={id:string;name:string;owner:"ME"|"WIFE";type:string;isSharedCash:boolean};
type Loan={id:string;lender:"ME"|"WIFE";borrower:"ME"|"WIFE";amount:number;repaidAmount:number;loanDate:string;description:string|null;status:string};
const name=(owner:string)=>owner==="ME"?"Ayya":"Sudu Manike";
export const dynamic="force-dynamic";
export default async function FamilyLoans({searchParams}:{searchParams:Promise<{advanced?:string;repaid?:string;error?:string}>}) {
  const viewer=await requireSession(),params=await searchParams;
  const [loanRows,accountRows]=await Promise.all([cashRows<any>("SELECT id,lender,borrower,amount,repaidAmount,loanDate,description,status FROM FamilyLoan ORDER BY status='PAID',loanDate DESC,createdAt DESC"),familyPaymentAccounts<any>()]);
  const loans=loanRows as Loan[], accounts=accountRows as Account[];
  const usable=accounts.filter(a=>!a.isSharedCash&&["CASH","BANK","SAVINGS"].includes(a.type));
  const mine=usable.filter(a=>a.owner===viewer), partner=usable.filter(a=>a.owner!==viewer),open=loans.filter(l=>l.status!=="PAID");
  return <><Nav/><main><div className="page-heading"><div><p className="eyebrow">Private cash advances</p><h1>Family loans</h1><p className="muted">Repayable cash moves between your selected accounts without becoming income or an expense.</p></div><Link className="button" href="/shared-cash">Shared cash for expenses</Link></div>
    {(params.advanced||params.repaid)&&<p role="status">{params.advanced?"Cash advance recorded and transferred.":"Repayment recorded, balances and loan outstanding updated."}</p>}{params.error&&<p role="alert">Check the selected accounts, amount, and outstanding balance.</p>}
    <section className="panel"><div className="section-heading"><div><h2>Give a repayable cash advance</h2><p className="muted">You lend from one of your accounts to your partner’s selected account.</p></div></div><form className="form-grid" action="/api/family-loans" method="post"><label>Give from<select name="accountId" required><option value="">Select your account</option>{mine.map(a=><option key={a.id} value={a.id}>{a.name} ({a.type})</option>)}</select></label><label>Give to {name(viewer==="ME"?"WIFE":"ME")}<select name="destinationAccountId" required><option value="">Select their account</option>{partner.map(a=><option key={a.id} value={a.id}>{a.name} ({a.type})</option>)}</select></label><label>Amount (LKR)<input name="amount" type="number" min="0.01" step="0.01" required/></label><label>Date<input name="transactionDate" type="date" defaultValue={dateValue(new Date())} required/></label><label className="span-2">Note<input name="description" maxLength={300} placeholder="Example: cash advance for vehicle repair"/></label><button className="button primary" disabled={!mine.length||!partner.length}>Give cash advance</button></form></section>
    <section className="panel"><div className="section-heading"><div><h2>Outstanding family loans</h2><p className="muted">Partial repayments are supported. Only the borrower can record a repayment.</p></div><strong>{lkr(open.reduce((sum,l)=>sum+Number(l.amount)-Number(l.repaidAmount),0))}</strong></div>{open.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Loan</th><th>Original</th><th>Repaid</th><th>Outstanding</th><th>Action</th></tr></thead><tbody>{open.map(loan=>{const outstanding=Number(loan.amount)-Number(loan.repaidAmount),canRepay=loan.borrower===viewer;return <tr key={loan.id}><td>{String(loan.loanDate).slice(0,10)}</td><td><strong>{name(loan.lender)} → {name(loan.borrower)}</strong><small>{loan.description||"Cash advance"}</small></td><td>{lkr(loan.amount)}</td><td>{lkr(loan.repaidAmount)}</td><td><strong>{lkr(outstanding)}</strong></td><td>{canRepay?<details><summary>Repay</summary><form className="form-grid" action="/api/family-loans/repay" method="post"><input type="hidden" name="loanId" value={loan.id}/><label>Pay from<select name="accountId" required><option value="">Select your account</option>{mine.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Return to {name(loan.lender)}<select name="destinationAccountId" required><option value="">Select their account</option>{partner.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Amount<input name="amount" type="number" min="0.01" max={outstanding} step="0.01" defaultValue={outstanding} required/></label><label>Date<input name="transactionDate" type="date" defaultValue={dateValue(new Date())} required/></label><label className="span-2">Note<input name="description" maxLength={300} placeholder="Optional repayment note"/></label><button className="button primary">Record repayment</button></form></details>:<span className="muted">Awaiting repayment from {name(loan.borrower)}</span>}</td></tr>})}</tbody></table></div>:<p className="empty">No outstanding family loans.</p>}</section>
  </main></>;
}
