import crypto from "node:crypto";
import { z } from "zod";
import { currentOwner, relativeRedirect } from "@/lib/auth";
import { requireApiSession } from "@/lib/route-auth";
import { transaction } from "@/lib/db";
import { validDate } from "@/lib/analytics";
const schema=z.object({accountId:z.string().min(1).max(191),debtor:z.string().trim().min(2).max(140),amount:z.coerce.number().positive().max(999999999).refine(n=>Math.round(n*100)===n*100),transactionDate:z.string().refine(validDate),description:z.string().max(300).optional()});
class InputError extends Error {}
export async function POST(request:Request){const denied=await requireApiSession();if(denied)return denied;const owner=await currentOwner(),parsed=schema.safeParse(Object.fromEntries((await request.formData()).entries()));if(!parsed.success)return relativeRedirect("/receivables?error=1");const d=parsed.data;try{await transaction(async c=>{const [accounts]=await c.execute<any[]>("SELECT id,owner,type FROM Account WHERE id=? AND isActive=1 FOR UPDATE",[d.accountId]),account=accounts[0];if(!account||account.owner!==owner||!["CASH","BANK","SAVINGS"].includes(account.type))throw new InputError();const id=crypto.randomUUID(),tx=crypto.randomUUID();await c.execute("INSERT INTO Receivable (id,owner,debtor,amount,receivableDate,description,updatedAt) VALUES (?,?,?,?,?,?,NOW(3))",[id,owner,d.debtor,d.amount,d.transactionDate,d.description||null]);await c.execute("INSERT INTO FinancialTransaction (id,type,status,amount,transactionDate,description,scope,owner,accountId,receivableId,updatedAt) VALUES (?,'RECEIVABLE_ADVANCE','POSTED',?,?,?,'PERSONAL',?,?,?,NOW(3))",[tx,d.amount,d.transactionDate,d.description||null,owner,d.accountId,id]);await c.execute("INSERT INTO AccountEntry (id,accountId,transactionId,amount,entryDate) VALUES (?,?,?,?,?)",[crypto.randomUUID(),d.accountId,tx,-d.amount,d.transactionDate]);});}catch(error){if(error instanceof InputError)return relativeRedirect("/receivables?error=1");throw error;}return relativeRedirect("/receivables?created=1");}
