import Link from "next/link";
import { Nav } from "@/components/nav";
import { requireSession } from "@/lib/auth";
import { rows } from "@/lib/db";
export const dynamic="force-dynamic";
function PartyForm({party}:{party?:any}){return <form className="form-grid" action="/api/parties" method="post">{party&&<input type="hidden" name="id" value={party.id}/>}<label>Name<input name="name" minLength={2} maxLength={140} required defaultValue={party?.name}/></label><label>Type<select name="kind" defaultValue={party?.kind||"SUPPLIER"}><option value="SUPPLIER">Supplier</option><option value="CUSTOMER">Customer</option><option value="BOTH">Customer & supplier</option></select></label><label>Contact number<input name="contactNo" type="tel" maxLength={40} defaultValue={party?.contactNo||""}/></label><label className="check"><input type="checkbox" name="isCash" defaultChecked={Boolean(party?.isCash)}/>Generic cash customer / supplier (no credit)</label><label className="check"><input type="checkbox" name="isActive" defaultChecked={party?Boolean(party.isActive):true}/>Active</label><button className="button primary">{party?"Save changes":"Create master record"}</button></form>}
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;error?:string;saved?:string}>}){
  await requireSession();const p=await searchParams,q=(p.q||"").trim();
  const parties=await rows<any>("SELECT * FROM Party WHERE name LIKE ? OR contactNo LIKE ? ORDER BY isActive DESC,name",[`%${q}%`,`%${q}%`]);
  return <><Nav/><main><div className="page-heading"><div><p className="eyebrow">Master data</p><h1>Customers & suppliers</h1><p className="muted">Customers and suppliers are shared between both logins. Each login sees only its own financial history. Save names and contact numbers once. Use named records for credit and generic Cash Supplier / Cash Customer records for cash transactions.</p></div><Link className="button" href="/master-data">Master data</Link></div>{p.error&&<p role="alert">Unable to save. Names must be unique; type and cash status cannot change after use. Deactivate records to preserve history.</p>}{p.saved&&<p role="status">Master record saved.</p>}<section className="panel"><h2>Add customer / supplier</h2><PartyForm/></section><section className="panel" style={{marginTop:20}}><form className="report-picker"><label>Search name or contact<input name="q" defaultValue={q}/></label><button className="button">Search</button><Link href="/master-data/parties">Reset</Link></form>{parties.map(p=><article key={p.id} style={{padding:"16px 0",borderBottom:"1px solid var(--line)"}}><div className="section-heading"><div><strong>{p.name}</strong><p>{p.kind} · {p.contactNo||"No contact number"} · {p.isActive?"Active":"Inactive"}{p.isCash?" · Cash only":""}</p></div><Link className="button" href={`/parties/${p.id}`}>View ledger</Link></div><details><summary>Edit record</summary><PartyForm party={p}/></details></article>)}{!parties.length&&<p>No matching customers or suppliers.</p>}</section></main></>;
}
