import crypto from "node:crypto";
import Link from "next/link";
import { Nav } from "@/components/nav";
import { requireSession } from "@/lib/auth";
import { rows } from "@/lib/db";
import { lkr } from "@/lib/format";
export const dynamic="force-dynamic";
export default async function BillsPage({searchParams}:{searchParams:Promise<{bill?:string;status?:string;owner?:string;error?:string;saved?:string}>}){
  const viewer=await requireSession();const p=await searchParams;
  const status=p.status==="paid"||p.status==="all"?p.status:"outstanding",owner=viewer;
  const clauses=["t.type='ACCRUED_EXPENSE'","t.status='POSTED'","a.status<>'VOID'"];const values:string[]=[];
  if(status==="outstanding")clauses.push("a.status IN ('OPEN','PARTIALLY_PAID') AND a.amount>a.paidAmount");
  if(status==="paid")clauses.push("a.status='PAID'");
  clauses.push("t.owner=?");values.push(owner);
  const bills=await rows<any>(`SELECT t.id,t.owner,t.scope,t.description,t.counterparty,t.transactionDate,a.amount,a.paidAmount,a.dueDate,a.status FROM FinancialTransaction t JOIN AccruedExpense a ON a.id=t.accrualId WHERE ${clauses.join(" AND ")} ORDER BY a.dueDate IS NULL,a.dueDate,t.transactionDate,t.id`,values);
  const selected=p.bill?(await rows<any>("SELECT t.id,t.owner,t.scope,t.partyId,t.description,t.counterparty,t.transactionDate,a.amount,a.paidAmount,a.dueDate,a.status FROM FinancialTransaction t JOIN AccruedExpense a ON a.id=t.accrualId WHERE t.id=? AND t.type='ACCRUED_EXPENSE' AND t.status='POSTED'",[p.bill]))[0]:null;
  const accounts=selected?await rows<any>("SELECT id,name,type FROM Account WHERE owner=? AND isActive=1 AND type IN ('CASH','BANK','SAVINGS','CREDIT_CARD') ORDER BY name",[selected.owner]):[];
  const payments=selected?await rows<any>("SELECT t.id,t.amount,t.transactionDate,t.description,a.name account FROM FinancialTransaction t LEFT JOIN Account a ON a.id=t.accountId WHERE t.settlesTransactionId=? AND t.status='POSTED' ORDER BY t.transactionDate,t.createdAt,t.id",[selected.id]):[];
  const outstanding=selected?Math.max(0,Math.round((Number(selected.amount)-Number(selected.paidAmount))*100)/100):0;
  const canPay=selected&&outstanding>0&&["OPEN","PARTIALLY_PAID"].includes(selected.status);
  const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Colombo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
  return <><Nav/><main><div className="page-heading"><div><p className="eyebrow">Pay later → Pay bill</p><h1>Pay-later bills</h1><p className="muted">Pay an outstanding bill in full or in parts. The expense was already recorded, so payment does not count it again.</p></div><Link className="button" href="/transactions/new?type=ACCRUED_EXPENSE">Add pay-later bill</Link></div>
    {p.saved&&<p role="status">Payment recorded. The remaining bill balance has been updated.</p>}{p.error&&<p role="alert">Unable to record payment. Check the remaining amount, payment date and account. The bill may already be paid.</p>}
    {p.bill&&!selected&&<p role="alert">This pay-later bill was not found.</p>}
    {selected&&<section className="panel" id="payment" style={{marginBottom:20}}><div className="section-heading"><div><h2>{selected.description||selected.counterparty||"Pay-later bill"}</h2><p className="muted">{selected.owner==="WIFE"?"Wife":"Me"} · {selected.scope==="BUSINESS"?"Business":"Personal"} · {selected.counterparty||"No supplier linked"}</p></div><Link href="/bills">Close bill</Link></div><div className="report-summary"><div><span>Original bill</span><strong>{lkr(selected.amount)}</strong></div><div><span>Already paid</span><strong>{lkr(selected.paidAmount)}</strong></div><div><span>Remaining</span><strong>{lkr(outstanding)}</strong></div></div>
      {canPay?<form className="form-grid" action="/api/parties/settle" method="post"><input type="hidden" name="returnTo" value="bills"/><input type="hidden" name="transactionId" value={selected.id}/><input type="hidden" name="submissionId" value={crypto.randomUUID()}/><label>Payment amount (LKR)<input name="amount" type="number" min="0.01" max={outstanding} step="0.01" defaultValue={outstanding} required/></label><label>Payment date<input name="transactionDate" type="date" min={String(selected.transactionDate).slice(0,10)} defaultValue={today} required/></label><label>Pay from<select name="accountId" defaultValue="" required><option value="">Select payment account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}{a.type==="CREDIT_CARD"?" (credit card)":""}</option>)}</select></label><label>Description (optional)<input name="description" maxLength={300} placeholder="Payment reference or note"/></label><button className="button primary" disabled={!accounts.length}>Record bill payment</button>{!accounts.length&&<p>Add an active payment account for {selected.owner==="WIFE"?"Wife":"Me"} in <Link href="/master-data?section=ACCOUNT">Master data</Link>.</p>}<p className="muted">Cash/bank payments reduce cash; credit-card payments increase card debt.</p></form>:<p>{selected.status==="VOID"?"This bill is void.":"This bill is fully paid."}</p>}
      <details open={!!p.saved}><summary>Payment history ({payments.length})</summary>{payments.length?<div className="table-wrap"><table><thead><tr><th>Date</th><th>Account</th><th>Description</th><th>Paid</th></tr></thead><tbody>{payments.map(payment=><tr key={payment.id}><td>{String(payment.transactionDate).slice(0,10)}</td><td>{payment.account||"No account"}</td><td>{payment.description}</td><td>{lkr(payment.amount)}</td></tr>)}</tbody></table></div>:<p>No linked payment records. Any historical paid amount is preserved above.</p>}</details>
    </section>}
    <section className="panel"><form className="report-picker"><label>Show<select name="status" defaultValue={status}><option value="outstanding">Outstanding bills</option><option value="paid">Paid bills</option><option value="all">All bills</option></select></label><button className="button">Apply</button></form><div className="table-wrap"><table><thead><tr><th>Bill / supplier</th><th>Owner</th><th>Due</th><th>Amount</th><th>Paid</th><th>Remaining</th><th>Action</th></tr></thead><tbody>{bills.map(b=>{const remaining=Math.max(0,Number(b.amount)-Number(b.paidAmount));return <tr key={b.id}><td>{b.description||"Pay-later bill"}<small>{b.counterparty||"No supplier linked"}</small></td><td>{b.owner==="WIFE"?"Wife":"Me"}</td><td>{b.dueDate?String(b.dueDate).slice(0,10):"Not set"}</td><td>{lkr(b.amount)}</td><td>{lkr(b.paidAmount)}</td><td>{lkr(remaining)}</td><td><Link className="button" href={`/bills?bill=${b.id}&status=${status}&owner=${owner}#payment`}>{remaining>0?"Pay bill":"View payments"}</Link></td></tr>})}{!bills.length&&<tr><td colSpan={7}>No bills match this filter.</td></tr>}</tbody></table></div></section>
  </main></>;
}
