"use client";
import { UNITS, moneyCents, normalizeItem } from "@/lib/expenses";
export type ItemOption={id:string;name:string;categoryId:string;defaultUnit:string|null};
export type DraftLine={key:string;name:string;categoryId:string;quantity:string;unit:string;amount:string};
export const newLine=():DraftLine=>({key:crypto.randomUUID(),name:"",categoryId:"",quantity:"",unit:"",amount:""});
export function ExpenseItems({lines,onChange,items,categories}:{lines:DraftLine[];onChange:(lines:DraftLine[])=>void;items:ItemOption[];categories:{id:string;name:string}[]}) {
  const total=lines.reduce((sum,l)=>sum+(Number.isFinite(Number(l.amount))?moneyCents(l.amount):0),0)/100;
  function update(key:string,patch:Partial<DraftLine>){onChange(lines.map(l=>l.key===key?{...l,...patch}:l))}
  return <div className="span-2 expense-items"><div className="section-heading"><div><h2>Expense items</h2><p className="muted">Type a new item or choose an existing one. Quantity is optional.</p></div><button type="button" className="button" onClick={()=>onChange([...lines,newLine()])}>Add item</button></div><input type="hidden" name="lines" value={JSON.stringify(lines.map(({key,...line})=>line))}/>{lines.map((line,index)=><div className="expense-item" key={line.key}><label>Item {index+1}<input list={`items-${line.key}`} value={line.name} maxLength={140} required onChange={e=>{const matches=items.filter(i=>normalizeItem(i.name)===normalizeItem(e.target.value));const match=matches.find(i=>i.categoryId===line.categoryId)??(matches.length===1?matches[0]:undefined);update(line.key,{name:e.target.value,...(match?{categoryId:match.categoryId,unit:match.defaultUnit||""}:{})})}}/><datalist id={`items-${line.key}`}>{items.filter(i=>!line.categoryId||i.categoryId===line.categoryId).map(i=><option key={i.id} value={i.name}/>)}</datalist></label><label>Expense category<select value={line.categoryId} required onChange={e=>update(line.key,{categoryId:e.target.value})}><option value="">Select category</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Quantity (optional)<input type="number" min="0.001" max="999999999" step="0.001" value={line.quantity} onChange={e=>update(line.key,{quantity:e.target.value})}/></label><label>Unit<select required={!!line.quantity} value={line.unit} onChange={e=>update(line.key,{unit:e.target.value})}><option value="">Select unit</option>{UNITS.map(u=><option key={u}>{u}</option>)}</select></label><label>Line amount (LKR)<input type="number" min="0.01" max="999999999" step="0.01" value={line.amount} required onChange={e=>update(line.key,{amount:e.target.value})}/>{Number(line.quantity)>0&&Number(line.amount)>0&&<small>{(Number(line.amount)/Number(line.quantity)).toFixed(2)} per {line.unit||"unit"}</small>}</label><button type="button" className="button" aria-label={`Remove item ${index+1}`} onClick={()=>onChange(lines.filter(l=>l.key!==line.key))}>Remove</button></div>)}<p><strong>Total: LKR {total.toFixed(2)}</strong></p>{!categories.length&&<p>Add an expense category in Master Data to start item tracking.</p>}</div>;
}
