"use client";
import Link from "next/link";
import { useState } from "react";
import { householdTotals,categorySpending,itemPurchases,shoppingPlan,monthOffset,monthEnd,csvText,type HouseholdLine,type Budget } from "@/lib/household";
import { analyticsMoney as money } from "@/lib/analytics";
type Category={id:string;name:string};
type Bill={id:string;owner:string;description:string|null;dueDate:string|null;amount:number|string};
const who=(owner:string)=>owner==="WIFE"?"Wife":"Me";
function download(name:string,data:unknown[][]){const url=URL.createObjectURL(new Blob([csvText(data)],{type:"text/csv;charset=utf-8"}));const a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}

export function Household({month,today,lines,budgets,categories,unpaid,notice}:{month:string;today:string;lines:HouseholdLine[];budgets:Budget[];categories:Category[];unpaid:Bill[];notice:string}) {
  const [owner,setOwner]=useState("ALL"),[category,setCategory]=useState(""),[query,setQuery]=useState(""),[page,setPage]=useState(0),[stock,setStock]=useState<Record<string,string>>({});
  const [from,setFrom]=useState(`${month}-01`),[to,setTo]=useState(month===today.slice(0,7)?today:monthEnd(month));
  const valid=from<=to&&from.startsWith(month)&&to.startsWith(month);
  const match=(l:HouseholdLine)=>(owner==="ALL"||l.owner===owner)&&(!category||l.categoryId===category)&&`${l.item||""} ${l.description||""} ${l.category} ${l.account||""}`.toLowerCase().includes(query.toLowerCase());
  const selected=valid?lines.filter(l=>l.status==="POSTED"&&l.household&&l.transactionDate>=from&&l.transactionDate<=to&&match(l)):[];
  const purchases=selected.filter(l=>l.type==="EXPENSE"),total=householdTotals(purchases),groups=categorySpending(purchases),items=itemPurchases(purchases);
  const allMonth=lines.filter(l=>l.household&&l.transactionDate.startsWith(month));
  const previous=monthOffset(month,-1),lastDay=Number(monthEnd(previous).slice(8));
  const previousFrom=`${previous}-${String(Math.min(Number(from.slice(8)),lastDay)).padStart(2,"0")}`;
  const previousTo=`${previous}-${String(Math.min(Number(to.slice(8)),lastDay)).padStart(2,"0")}`;
  const previousLines=valid?lines.filter(l=>l.household&&l.transactionDate>=previousFrom&&l.transactionDate<=previousTo&&match(l)):[];
  const previousTotal=householdTotals(previousLines).total,change=total.total-previousTotal;
  const previousItems=itemPurchases(previousLines),previousCategories=categorySpending(previousLines);
  const months=Array.from({length:6},(_,i)=>monthOffset(month,i-5)).map(m=>({month:m,...householdTotals(lines.filter(l=>l.transactionDate.startsWith(m)&&match(l)))}));
  const trendMax=Math.max(1,...months.map(m=>m.total));
  const plans=shoppingPlan(lines,month);
  const plansAdjusted=plans.map(p=>{const key=`${p.id}:${p.unit}`,onHand=Math.max(0,Number(stock[key])||0);return {...p,key,onHand,buy:Math.max(0,Math.round((p.monthlyQuantity-onHand)*1000)/1000)}});
  const classify=[...new Map(lines.filter(l=>l.status==="POSTED"&&l.transactionDate.startsWith(month)).map(l=>[l.transactionId,l])).values()];
  const [classifyQuery,setClassifyQuery]=useState("");
  const [classifyPage,setClassifyPage]=useState(0);
  const classifyRows=classify.filter(l=>`${l.description||""} ${l.account||""}`.toLowerCase().includes(classifyQuery.toLowerCase()));
  const [budgetCategory,setBudgetCategory]=useState("");
  function resetPage(){setPage(0)}
  function exportPurchases(){download(`household-${from}-to-${to}.csv`,[["Household purchases",from,to],["Payer filter",owner],["Category filter",categories.find(c=>c.id===category)?.name||"All"],["Search",query],["Date","Payer","Description","Account","Category","Item","Quantity","Unit","Amount (LKR)"],...purchases.map(l=>[l.transactionDate,who(l.owner),l.description,l.account,l.category,l.item,l.quantity,l.unit,l.amount]),["Total",total.total],["My portion",total.me],["Wife portion",total.wife]])}
  const budgetTotal=budgets.find(b=>!b.categoryKey),fullMonthTotal=householdTotals(allMonth).total;
  return <>
    <div className="page-heading"><div><p className="eyebrow">Family spending & purchase planning</p><h1>Household</h1><p className="muted">See what the family spends, who paid, and what to buy next.</p></div><div className="hh-actions"><Link className="button primary" href="/transactions/new?type=EXPENSE&household=1&owner=ME">Add my expense</Link><Link className="button" href="/transactions/new?type=EXPENSE&household=1&owner=WIFE">Add wife’s expense</Link></div></div>
    {notice&&<p className="analytics-alert" role="status">{notice}</p>}
    <nav className="analytics-sections" aria-label="Household sections"><a href="#purchases">Expenses</a><a href="#items">Items</a><a href="#shopping">Shopping plan</a><a href="#budgets">Budgets</a><a href="#classify">Manage household labels</a><Link href="/master-data/items">Item Master</Link></nav>
    <section className="panel"><form className="report-picker"><label>Reporting month<input name="month" type="month" defaultValue={month} required/></label><button className="button primary">View month</button></form><div className="analytics-filters"><label>From<input type="date" value={from} min={`${month}-01`} max={monthEnd(month)} onChange={e=>{setFrom(e.target.value);resetPage()}}/></label><label>To<input type="date" value={to} min={`${month}-01`} max={monthEnd(month)} onChange={e=>{setTo(e.target.value);resetPage()}}/></label><label>Paid by<select value={owner} onChange={e=>{setOwner(e.target.value);resetPage()}}><option value="ALL">Me & wife</option><option value="ME">Me</option><option value="WIFE">Wife</option></select></label><label>Expense category<select value={category} onChange={e=>{setCategory(e.target.value);resetPage()}}><option value="">All categories</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Search<input value={query} placeholder="Item, description or account" onChange={e=>{setQuery(e.target.value);resetPage()}}/></label></div>{!valid&&<p role="alert">Choose a valid date range within this reporting month.</p>}</section>
    <section className="metric-grid"><Metric title="Household paid expenses" amount={total.total} note={`${total.count} purchases · selected filters`}/><Metric title="My portion" amount={total.me} note={`${total.total?(total.me/total.total*100).toFixed(1):0}% of selected spending`}/><Metric title="Wife’s portion" amount={total.wife} note={`${total.total?(total.wife/total.total*100).toFixed(1):0}% of selected spending`}/><Metric title="Change from previous month" amount={change} note={`Compared with ${previousFrom} to ${previousTo}${previousTotal?` · ${(change/previousTotal*100).toFixed(1)}%`:" · no earlier spending recorded"}`}/></section>
    <div className="two-column"><section className="panel"><h2>Monthly spending by payer</h2><p className="muted">Six months · payer, category and search filters apply. Current month may be incomplete.</p><div className="hh-trend">{months.map(m=><div key={m.month}><span>{m.month}</span><div className="hh-bar" role="img" aria-label={`${m.month}: me ${money(m.me)}, wife ${money(m.wife)}`}><i style={{width:`${m.me/trendMax*100}%`}}/><i className="wife" style={{width:`${m.wife/trendMax*100}%`}}/></div><small>Me {money(m.me)} · Wife {money(m.wife)}</small></div>)}</div></section><section className="panel"><h2>Where costs increased</h2><p className="muted">Selected dates versus the matching dates last month.</p>{groups.map(g=>({...g,increase:g.total-(previousCategories.find(p=>p.id===g.id)?.total||0)})).filter(g=>g.increase>0).sort((a,b)=>b.increase-a.increase).slice(0,5).map(g=><p key={g.id}><strong>{g.name}</strong> +{money(g.increase)}</p>)}<div className="table-wrap"><table><thead><tr><th>Category</th><th>Me</th><th>Wife</th><th>Total</th></tr></thead><tbody>{groups.map(g=><tr key={g.id}><td>{g.name}</td><td>{money(g.me)}</td><td>{money(g.wife)}</td><td>{money(g.total)}</td></tr>)}</tbody></table></div>{!groups.length&&<p>No household purchases match this selection.</p>}</section></div>
    <section className="panel" id="purchases"><div className="section-heading"><h2>Household expense list</h2><button className="button" disabled={!valid} onClick={exportPurchases}>Export CSV</button></div><p className="muted">Item lines add up to each purchase total. Bills recorded as pay later appear separately below.</p><div className="table-wrap"><table><thead><tr><th>Date</th><th>Item / description</th><th>Category</th><th>Paid by / account</th><th>Quantity</th><th>Amount</th></tr></thead><tbody>{purchases.slice(page*25,(page+1)*25).map(l=><tr key={l.id}><td>{l.transactionDate}</td><td>{l.item||l.description||"Expense"}{l.item&&l.description&&<small>{l.description}</small>}</td><td>{l.category}</td><td>{who(l.owner)}<small>{l.account||"No account"}</small></td><td>{l.quantity==null?"Not recorded":`${Number(l.quantity)} ${l.unit}`}</td><td>{money(l.amount)}</td></tr>)}</tbody></table></div>{!purchases.length&&<p>No household purchases in this selection. Mark existing expenses below or add a new expense.</p>}<Pager page={page} count={purchases.length} setPage={setPage}/></section>
    <section className="panel" id="items"><h2>Monthly item purchases</h2><p className="muted">Purchased quantities, not consumption. Missing quantities count toward spending but are excluded from unit-cost calculations. Grams and millilitres are converted to kg and litres; packs stay separate.</p><div className="table-wrap"><table><thead><tr><th>Item</th><th>Purchased quantity</th><th>Previous period quantity</th><th>Total cost</th><th>Average unit cost</th><th>Missing quantity</th></tr></thead><tbody>{items.map(i=><tr key={`${i.id}:${i.unit}`}><td>{i.name}</td><td>{i.quantity>0?`${i.quantity} ${i.unit}`:"Not recorded"}</td><td>{previousItems.find(p=>p.id===i.id&&p.unit===i.unit)?.quantity??0} {i.unit==="unspecified"?"":i.unit}</td><td>{money(i.spend)}</td><td>{i.unitCost==null?"—":`${money(i.unitCost)} / ${i.unit}`}</td><td>{i.missing} entries</td></tr>)}</tbody></table></div>{!items.length&&<p>No item details for these purchases yet. Use “Add item details” when entering an expense.</p>}</section>
    <section className="panel" id="shopping"><div className="section-heading"><h2>Shopping estimate for {month}</h2><button className="button" onClick={()=>download(`shopping-plan-${month}.csv`,[["Item","Unit","Three-month average quantity","Stock on hand","Suggested purchase","Estimated cost"],...plansAdjusted.map(p=>[p.name,p.unit,p.monthlyQuantity,p.onHand,p.buy,p.unitCost==null?"":(p.buy*p.unitCost).toFixed(2)])])}>Export shopping list</button></div><p className="muted">Both payers, all categories. Uses the three complete months before {month}, including months with no purchases. Select next month above to plan ahead. Enter stock on hand to reduce the estimate; these adjustments stay on this page until refreshed. Purchase history can include stockpiling, so review the estimate before buying.</p><div className="table-wrap"><table><thead><tr><th>Item</th><th>Monthly average</th><th>Stock on hand</th><th>Suggested purchase</th><th>Estimated cost</th></tr></thead><tbody>{plansAdjusted.map(p=><tr key={p.key}><td>{p.name}<small>{p.missing?`${p.missing} entries without quantity excluded`:"Known quantities only"}</small></td><td>{p.monthlyQuantity} {p.unit}</td><td><input aria-label={`Stock on hand for ${p.name} in ${p.unit}`} type="number" min="0" step="0.001" value={stock[p.key]||""} onChange={e=>setStock({...stock,[p.key]:e.target.value})}/></td><td>{p.buy} {p.unit}</td><td>{p.unitCost==null?"—":money(p.buy*p.unitCost)}</td></tr>)}</tbody></table></div>{!plans.length&&<p>Record quantities in previous months to build a shopping estimate.</p>}</section>
    <section className="panel" id="budgets"><h2>Household budgets · {month}</h2><p className="muted">Full month, both payers, all paid household expenses. Search and date filters above do not change budgets. Category budgets are separate limits within the overall budget.</p>{budgetTotal&&<p><strong>{money(Number(budgetTotal.amount)-fullMonthTotal)} remaining</strong> · {money(fullMonthTotal)} spent of {money(budgetTotal.amount)}</p>}<form className="analytics-filters" action="/api/household" method="post"><input type="hidden" name="intent" value="budget"/><input type="hidden" name="month" value={month}/><label>Budget for<select name="categoryKey" value={budgetCategory} onChange={e=>setBudgetCategory(e.target.value)}><option value="">Overall household</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Monthly limit (LKR)<input key={budgetCategory} type="number" name="amount" min="0" max="999999999" step="0.01" required defaultValue={budgets.find(b=>b.categoryKey===budgetCategory)?.amount??""}/></label><button className="button primary">Save budget</button></form>{budgets.map(b=>{const spent=b.categoryKey?categorySpending(allMonth).find(g=>g.id===b.categoryKey)?.total||0:fullMonthTotal;return <p key={b.categoryKey}><strong>{categories.find(c=>c.id===b.categoryKey)?.name||"Overall household"}</strong> · {money(spent)} / {money(b.amount)} · {spent>Number(b.amount)?`${money(spent-Number(b.amount))} over budget`:`${money(Number(b.amount)-spent)} remaining`}</p>})}</section>
    <section className="panel"><h2>Outstanding household bills</h2><p className="muted">All unpaid household bills across all dates; excluded from paid-spending totals and shopping quantities.</p><p>Total outstanding: <strong>{money(unpaid.reduce((sum,b)=>sum+Number(b.amount),0))}</strong></p>{unpaid.map(b=><p key={b.id}>{b.description||"Unpaid bill"} · {who(b.owner)} · {money(b.amount)} · Due {b.dueDate||"not set"} · <Link className="button" href={`/bills?bill=${b.id}#payment`}>Pay bill</Link></p>)}{!unpaid.length&&<p>No unpaid household bills recorded.</p>}</section>
    <section className="panel" id="classify"><h2>Manage household labels · {month}</h2><p className="muted">All posted expenses in this month, including business expenses. Mark older expenses as Household here. Actual and tax labels stay unchanged.</p><input aria-label="Search expenses to classify" placeholder="Search description or account" value={classifyQuery} onChange={e=>{setClassifyQuery(e.target.value);setClassifyPage(0)}}/><div className="table-wrap"><table><thead><tr><th>Date</th><th>Description</th><th>Owner</th><th>Household label</th></tr></thead><tbody>{classifyRows.slice(classifyPage*25,(classifyPage+1)*25).map(l=><tr key={l.transactionId}><td>{l.transactionDate}</td><td>{l.description||"Expense"}<small>{l.account} · {l.type==="ACCRUED_EXPENSE"?"Pay later":"Paid"}</small></td><td>{who(l.owner)}</td><td><form action="/api/household" method="post" className="hh-actions"><input type="hidden" name="intent" value="label"/><input type="hidden" name="id" value={l.transactionId}/><input type="hidden" name="month" value={month}/><label><input name="household" type="checkbox" defaultChecked={Boolean(l.household)}/> Household</label><button className="button">Save</button></form></td></tr>)}</tbody></table></div><Pager page={classifyPage} count={classifyRows.length} setPage={setClassifyPage}/></section>
    <p className="analytics-note">Your main dashboard and analytics continue to show your finances. Wife spending is recorded here without income or a cash balance. Tax labels do not affect household reports.</p>
  </>;
}
function Metric({title,amount,note}:{title:string;amount:number;note:string}){return <article className="metric"><p>{title}</p><strong>{money(amount)}</strong><small>{note}</small></article>}
function Pager({page,count,setPage}:{page:number;count:number;setPage:(p:number)=>void}){return <div className="hh-actions"><button className="button" disabled={page===0} onClick={()=>setPage(page-1)}>Previous</button><span>{count?`${page*25+1}–${Math.min(count,(page+1)*25)} of ${count}`:"0 entries"}</span><button className="button" disabled={(page+1)*25>=count} onClick={()=>setPage(page+1)}>Next</button></div>}
