"use client";

import { useState } from "react";

type Project = { id: string; name: string; isActive: number | boolean };
type Category = { id: string; name: string; scope: "PERSONAL" | "BUSINESS" | null; isActive: number | boolean };
type Task = { id: string; name: string; scope: "PERSONAL" | "BUSINESS"; projectId: string | null; isActive: number | boolean };
type Section = "PROJECT" | "CATEGORY" | "TASK";

function Hidden({ entity, intent, id }: { entity: Section; intent: "create" | "update" | "delete"; id?: string }) { return <><input name="entity" type="hidden" value={entity} /><input name="intent" type="hidden" value={intent} />{id && <input name="id" type="hidden" value={id} />}</>; }
function Active({ value }: { value?: number | boolean }) { return <label className="check"><input defaultChecked={value !== false && value !== 0} name="isActive" type="checkbox" />Active</label>; }

export function MasterData({ projects, categories, tasks }: { projects: Project[]; categories: Category[]; tasks: Task[] }) {
  const [section, setSection] = useState<Section>("PROJECT");
  return <div className="master-layout"><div className="master-nav" aria-label="Master record types"><button className={section === "PROJECT" ? "active" : ""} onClick={() => setSection("PROJECT")} type="button">Projects</button><button className={section === "CATEGORY" ? "active" : ""} onClick={() => setSection("CATEGORY")} type="button">Categories</button><button className={section === "TASK" ? "active" : ""} onClick={() => setSection("TASK")} type="button">Tasks</button></div><section className="panel master-content">{section === "PROJECT" && <Projects projects={projects} />}{section === "CATEGORY" && <Categories categories={categories} />}{section === "TASK" && <Tasks projects={projects} tasks={tasks} />}</section></div>;
}

function Projects({ projects }: { projects: Project[] }) { return <><div className="section-heading"><div><p className="eyebrow">Master file</p><h2>Projects</h2></div></div><form action="/api/master-data" className="master-form" method="post"><Hidden entity="PROJECT" intent="create" /><label>Name<input maxLength={120} name="name" placeholder="Project name" required /></label><Active /><button className="button primary" type="submit">Add project</button></form><div className="master-list">{projects.map((project) => <article className="master-row" key={project.id}><div><strong>{project.name}</strong><span>{project.isActive ? "Active" : "Inactive"}</span></div><details><summary>Edit</summary><form action="/api/master-data" className="master-edit" method="post"><Hidden entity="PROJECT" id={project.id} intent="update" /><label>Name<input defaultValue={project.name} maxLength={120} name="name" required /></label><Active value={project.isActive} /><div className="master-actions"><button className="button primary" type="submit">Save</button></div></form><form action="/api/master-data" className="master-actions" method="post"><Hidden entity="PROJECT" id={project.id} intent="delete" /><button className="button danger" type="submit">Delete project</button></form></details></article>)}</div>{!projects.length && <div className="empty">No projects yet.</div>}</>; }

function Categories({ categories }: { categories: Category[] }) { return <><div className="section-heading"><div><p className="eyebrow">Master file</p><h2>Categories</h2></div></div><form action="/api/master-data" className="master-form" method="post"><Hidden entity="CATEGORY" intent="create" /><label>Name<input maxLength={100} name="name" placeholder="Category name" required /></label><label>Scope<select defaultValue="" name="scope"><option value="">Both personal and business</option><option value="PERSONAL">Personal</option><option value="BUSINESS">Business</option></select></label><Active /><button className="button primary" type="submit">Add category</button></form><div className="master-list">{categories.map((category) => <article className="master-row" key={category.id}><div><strong>{category.name}</strong><span>{category.scope ? `${category.scope.toLowerCase()} · ` : "All scopes · "}{category.isActive ? "Active" : "Inactive"}</span></div><details><summary>Edit</summary><form action="/api/master-data" className="master-edit" method="post"><Hidden entity="CATEGORY" id={category.id} intent="update" /><label>Name<input defaultValue={category.name} maxLength={100} name="name" required /></label><label>Scope<select defaultValue={category.scope || ""} name="scope"><option value="">Both personal and business</option><option value="PERSONAL">Personal</option><option value="BUSINESS">Business</option></select></label><Active value={category.isActive} /><div className="master-actions"><button className="button primary" type="submit">Save</button></div></form><form action="/api/master-data" className="master-actions" method="post"><Hidden entity="CATEGORY" id={category.id} intent="delete" /><button className="button danger" type="submit">Delete category</button></form></details></article>)}</div>{!categories.length && <div className="empty">No categories yet.</div>}</>; }

function Tasks({ projects, tasks }: { projects: Project[]; tasks: Task[] }) { const projectName = new Map(projects.map((project) => [project.id, project.name])); return <><div className="section-heading"><div><p className="eyebrow">Master file</p><h2>Tasks</h2></div></div><form action="/api/master-data" className="master-form" method="post"><Hidden entity="TASK" intent="create" /><label>Name<input maxLength={140} name="name" placeholder="Task name" required /></label><label>Scope<select defaultValue="PERSONAL" name="scope"><option value="PERSONAL">Personal</option><option value="BUSINESS">Business</option></select></label><label>Project<select defaultValue="" name="projectId"><option value="">No project</option>{projects.filter((project) => project.isActive).map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><Active /><button className="button primary" type="submit">Add task</button></form><div className="master-list">{tasks.map((task) => <article className="master-row" key={task.id}><div><strong>{task.name}</strong><span>{task.scope.toLowerCase()}{task.projectId ? ` · ${projectName.get(task.projectId) || "Archived project"}` : ""}{task.isActive ? " · Active" : " · Inactive"}</span></div><details><summary>Edit</summary><form action="/api/master-data" className="master-edit" method="post"><Hidden entity="TASK" id={task.id} intent="update" /><label>Name<input defaultValue={task.name} maxLength={140} name="name" required /></label><label>Scope<select defaultValue={task.scope} name="scope"><option value="PERSONAL">Personal</option><option value="BUSINESS">Business</option></select></label><label>Project<select defaultValue={task.projectId || ""} name="projectId"><option value="">No project</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</select></label><Active value={task.isActive} /><div className="master-actions"><button className="button primary" type="submit">Save</button></div></form><form action="/api/master-data" className="master-actions" method="post"><Hidden entity="TASK" id={task.id} intent="delete" /><button className="button danger" type="submit">Delete task</button></form></details></article>)}</div>{!tasks.length && <div className="empty">No tasks yet.</div>}</>; }
