import Link from "next/link";
import { ExportIncomeStatement } from "@/components/export-income-statement";
import { RowDataPacket } from "mysql2";
import { Nav } from "@/components/nav";
import { AnalyticsBreakdown } from "@/components/analytics-breakdown";
import { requireSession } from "@/lib/auth";
import { rows } from "@/lib/db";
import { analyticsMoney as lkr } from "@/lib/analytics";
import { AnalyticsRow, groupBy, summarize, validDate, goalMetrics } from "@/lib/analytics";
export const dynamic = "force-dynamic";
type Option = RowDataPacket & { id: string; name: string };
export default async function Analytics({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await requireSession();
  const params = await searchParams;
  const text = (key: string) => typeof params[key] === "string" ? params[key] as string : "";
  const today = new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Colombo", year: "numeric", month: "2-digit", day: "2-digit" }).format(new Date());
  const start = text("start") || `${today.slice(0, 7)}-01`, end = text("end") || today;
  const valid = validDate(start) && validDate(end) && start <= end;
  const scope = ["PERSONAL", "BUSINESS"].includes(text("scope")) ? text("scope") : "";
  const filters = ["t.owner='ME'","t.transactionDate >= ?", "t.transactionDate <= ?"];
  const values: string[] = [valid ? start : today, valid ? end : today];
  if (scope) { filters.push("t.scope=?"); values.push(scope); }
  for (const key of ["projectId", "categoryId", "taskId"]) if (text(key)) { filters.push(`t.${key}=?`); values.push(text(key)); }
  const [projects, categories, tasks, grouped, pendingRows, balances, accruals, settings, receivables] = await Promise.all([
    rows<Option>("SELECT id,name FROM Project ORDER BY name"), rows<Option>("SELECT id,name FROM Category ORDER BY name"), rows<Option>("SELECT id,name FROM Task ORDER BY name"),
    valid ? rows<RowDataPacket & AnalyticsRow>(`SELECT DATE_FORMAT(t.transactionDate,'%Y-%m') month,t.scope,COALESCE(p.name,'No project') project,COALESCE(c.name,'Uncategorized') category,COALESCE(k.name,'No task') task,
      SUM(CASE WHEN t.type='INCOME' THEN t.amount ELSE 0 END) income,
      SUM(CASE WHEN t.type IN ('EXPENSE','ACCRUED_EXPENSE') THEN t.amount ELSE 0 END) expenses, COUNT(*) count
      FROM IncomeExpenseActivity t LEFT JOIN Project p ON p.id=t.projectId LEFT JOIN Category c ON c.id=t.categoryId LEFT JOIN Task k ON k.id=t.taskId
      WHERE t.status='POSTED' AND t.type IN ('INCOME','EXPENSE','ACCRUED_EXPENSE') AND ${filters.join(" AND ")}
      GROUP BY month,t.scope,t.projectId,p.name,t.categoryId,c.name,t.taskId,k.name`, values) : Promise.resolve([]),
    valid ? rows<RowDataPacket>(`SELECT COUNT(*) count FROM FinancialTransaction t WHERE t.status='PENDING_REVIEW' AND ${filters.join(" AND ")}`, values) : Promise.resolve([]),
    rows<RowDataPacket>("SELECT a.id,a.name,a.type,COALESCE(SUM(e.amount),0) balance FROM Account a LEFT JOIN AccountEntry e ON e.accountId=a.id WHERE a.owner='ME' GROUP BY a.id ORDER BY a.name"),
    rows<RowDataPacket>("SELECT COALESCE(SUM(GREATEST(amount-paidAmount,0)),0) amount FROM AccruedExpense WHERE owner='ME' AND status IN ('OPEN','PARTIALLY_PAID')"),
    rows<RowDataPacket>("SELECT value FROM AppSetting WHERE `key`='analyticsGoals'"),
    rows<RowDataPacket>("SELECT COALESCE(SUM(GREATEST(balance,0)),0) amount FROM CreditOutstanding WHERE owner='ME' AND type='INCOME'")
  ]);
  const data: AnalyticsRow[] = grouped.map(row => ({ month: row.month, scope: row.scope, project: row.project, category: row.category, task: row.task, income: Number(row.income), expenses: Number(row.expenses), count: Number(row.count) }));
  const total = summarize(data), months = groupBy(data, "month"), categoryGroups = groupBy(data, "category"), scopes = groupBy(data, "scope");
  // Include months with no records so gaps remain visible in the trend.
  if (valid) { let cursor = new Date(`${start.slice(0,7)}-01T00:00:00Z`); const last = end.slice(0,7); while (cursor.toISOString().slice(0,7) <= last) { const name = cursor.toISOString().slice(0,7); if (!months.some(month => month.name === name)) months.push({ name, income: 0, expenses: 0, net: 0, count: 0 }); cursor.setUTCMonth(cursor.getUTCMonth()+1); } months.sort((a,b) => a.name.localeCompare(b.name)); }
  const loans = balances.filter(a => ["LOAN","CREDIT_CARD"].includes(a.type));
  const debt = loans.reduce((sum,a) => sum + Math.max(0,Number(a.balance)),0);
  const assets = balances.filter(a => !["LOAN","CREDIT_CARD"].includes(a.type)).reduce((sum,a) => sum + Number(a.balance),0) + loans.reduce((sum,a) => sum + Math.max(0,-Number(a.balance)),0);
  const unpaid = Number(accruals[0]?.amount ?? 0), netWorth = assets + Number(receivables[0]?.amount??0) - debt - unpaid;
  let goal = { target: 30000000, monthlyDebt: 0, monthlyWealth: 0 };
  try { const saved = JSON.parse(settings[0]?.value ?? "null"); if (saved && Number.isFinite(saved.target) && saved.target > 0 && Number.isFinite(saved.monthlyDebt) && saved.monthlyDebt >= 0 && Number.isFinite(saved.monthlyWealth) && saved.monthlyWealth >= 0) goal = saved; } catch { /* Use starting targets if settings are missing or invalid. */ }
  const metrics = goalMetrics(netWorth, debt, goal.target, goal.monthlyDebt, goal.monthlyWealth);
  const maxTrend = Math.max(1, ...months.flatMap(m => [m.income,m.expenses]));
  for (const name of (scope ? [scope] : ["BUSINESS", "PERSONAL"])) { if (!scopes.some(s => s.name === name)) scopes.push({ name, income: 0, expenses: 0, net: 0, count: 0 }); }
  const maxScope = Math.max(1,...scopes.flatMap(s => [s.income,s.expenses]));
  const selectedFilters = [scope || "Personal & business", projects.find(p => p.id === text("projectId"))?.name, categories.find(c => c.id === text("categoryId"))?.name, tasks.find(t => t.id === text("taskId"))?.name].filter(Boolean).join(" · ");
  return <><Nav /><main className="analytics-page"><div className="page-heading"><div><p className="eyebrow">Understand · Plan · Progress</p><h1>Analytics center</h1><p className="muted">See what earns, what costs, and how far you are from your next milestone.</p></div><Link className="button" href="/reports">Account statements</Link></div>
    <nav className="analytics-sections" aria-label="Analytics sections"><a href="#performance">Performance</a><a href="#statement">Income statement</a><Link href="/reports/tax">Income tax reports</Link><a href="#goals">Financial goals</a></nav>
    <section className="panel" id="performance"><form className="analytics-filters" action="/analytics"><label>From<input type="date" name="start" defaultValue={validDate(start) ? start : ""} required /></label><label>To<input type="date" name="end" defaultValue={validDate(end) ? end : ""} required /></label><label>Scope<select name="scope" defaultValue={scope}><option value="">Personal & business</option><option value="BUSINESS">Business</option><option value="PERSONAL">Personal</option></select></label>{([['projectId','Project',projects],['categoryId','Category',categories],['taskId','Task',tasks]] as const).map(([key,label,options]) => <label key={key}>{label}<select name={key} defaultValue={text(key)}><option value="">All {label === "Category" ? "categories" : `${label.toLowerCase()}s`}</option>{options.map(option => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label>)}<button className="button primary" type="submit">Apply filters</button><Link className="button" href="/analytics">Reset</Link></form><div className="analytics-presets"><Link href={`/analytics?start=${today.slice(0,4)}-01-01&end=${today}`}>Year to date</Link><Link href={`/analytics?start=${today.slice(0,7)}-01&end=${today}`}>This month</Link><span>Dates are inclusive. Presets reset other filters.</span></div></section>
    {!valid && <p role="alert" className="analytics-alert">Choose valid dates with the From date on or before the To date.</p>}
    <p className="analytics-context">{valid ? `${start} to ${end}` : "Invalid date range"} · {selectedFilters} · {total.count} confirmed income/expense lines</p>
    {Number(pendingRows[0]?.count ?? 0) > 0 && <p className="analytics-alert"><Link href="/review">{pendingRows[0].count} pending records</Link> in this selection are excluded until confirmed.</p>}
    <section className="metric-grid"><article className="metric positive"><p>Income</p><strong>{lkr(total.income)}</strong><small>Confirmed income, including credit sales</small></article><article className="metric negative"><p>Expenses</p><strong>{lkr(total.expenses)}</strong><small>Paid expenses + bills recorded as pay later</small></article><article className={`metric ${total.net >= 0 ? 'positive' : 'negative'}`}><p>Net result</p><strong>{lkr(total.net)}</strong><small>Income less recorded expenses</small></article><article className="metric"><p>Surplus margin</p><strong>{total.income > 0 ? `${(total.net / total.income * 100).toFixed(1)}%` : "—"}</strong><small>Net result divided by income</small></article></section>
    {!total.count && <div className="panel empty"><p>No confirmed income or expenses in this selection. Try a wider date range or fewer filters.</p><Link href="/transactions/new">Add a record</Link></div>}
    <div className="analytics-chart-grid"><section className="panel"><div className="section-heading"><div><p className="eyebrow">Monthly trend</p><h2>Income & expenses</h2></div></div><p className="analytics-legend"><span>● Income</span><span>● Expenses</span></p><div className="analytics-trend" role="img" aria-label={months.map(m => `${m.name}: income ${lkr(m.income)}, expenses ${lkr(m.expenses)}`).join('; ') || 'No data'}>{months.map(month => <div className="analytics-month" key={month.name}><div className="analytics-bars"><div title={`Income ${lkr(month.income)}`} style={{height:`${month.income/maxTrend*100}%`}} /><div title={`Expenses ${lkr(month.expenses)}`} style={{height:`${month.expenses/maxTrend*100}%`}} /></div><small>{month.name}</small></div>)}</div><details className="analytics-chart-data"><summary>View chart values</summary>{months.map(m => <p key={m.name}>{m.name}: income {lkr(m.income)} · expenses {lkr(m.expenses)}</p>)}</details></section>
    <section className="panel"><p className="eyebrow">Across your finances</p><h2>Business vs personal</h2><div className="analytics-scope-chart">{scopes.map(s => <div key={s.name}><strong>{s.name === 'BUSINESS' ? 'Business' : 'Personal'}</strong><div className="analytics-horizontal"><i style={{width:`${s.income/maxScope*100}%`}} /></div><small>Income {lkr(s.income)}</small><div className="analytics-horizontal expense"><i style={{width:`${s.expenses/maxScope*100}%`}} /></div><small>Expenses {lkr(s.expenses)} · Net {lkr(s.net)}</small></div>)}{!scopes.length && <p className="muted">No activity to compare.</p>}</div></section></div>
    <section className="panel" id="statement"><div className="section-heading"><div><p className="eyebrow">Selected period & filters</p><h2>Income statement</h2></div><ExportIncomeStatement rows={data} context={`${start} to ${end} · ${selectedFilters}`} /></div><div className="table-wrap"><table><thead><tr><th>Category</th><th>Income</th><th>Expenses</th><th>Net</th></tr></thead><tbody>{categoryGroups.map(c => <tr key={c.name}><td>{c.name}</td><td>{lkr(c.income)}</td><td>{lkr(c.expenses)}</td><td>{lkr(c.net)}</td></tr>)}{!categoryGroups.length && <tr><td colSpan={4} className="empty-cell">No statement activity for these filters.</td></tr>}</tbody><tfoot><tr><th>Total</th><td>{lkr(total.income)}</td><td>{lkr(total.expenses)}</td><td><strong>{lkr(total.net)}</strong></td></tr></tfoot></table></div><p className="analytics-note">Management statement based on actual labels. Transfers, debt payments, opening balances, adjustments, pending and void records are excluded. Pay-later bills count as expenses when recorded. Record interest, fees and taxes as separate expenses; debt payments are not automatically split into principal and interest. This is not a cash-flow statement.</p></section>
    <AnalyticsBreakdown rows={data} />
    <section className="panel analytics-goals" id="goals"><div className="section-heading"><div><p className="eyebrow">Your financial direction</p><h2>From debt-free to {lkr(goal.target)}</h2><p className="muted recent-subtitle">Current all-time position across your accounts, including inactive accounts. Date and activity filters do not apply here.</p></div></div>
    {params.goalSaved && <p role="status" className="analytics-alert">Financial targets saved.</p>}{params.goalError && <p role="alert" className="analytics-alert">Enter a positive wealth target and non-negative monthly amounts.</p>}
    <div className="analytics-goal-grid"><article><span className="eyebrow">01 · Clear borrowing</span><h3>Become debt-free</h3><strong className="analytics-big">{lkr(debt)}</strong><p>Loans & credit cards remaining</p><p>{metrics.debtMonths === 0 ? "No recorded loan or card balance remains." : metrics.debtMonths === null ? "Set a monthly repayment amount to model your timeline." : `About ${metrics.debtMonths} months at ${lkr(goal.monthlyDebt)} / month, before interest and new borrowing.`}</p><details><summary>View debt balances</summary>{loans.filter(l => Number(l.balance)>0).map(l => <p key={l.id}>{l.name}: {lkr(l.balance)}</p>)}</details></article><article><span className="eyebrow">02 · Build wealth</span><h3>Net worth target</h3><strong className="analytics-big">{lkr(netWorth)}</strong><p>Current net worth · {lkr(metrics.gap)} to target</p><progress aria-label="Net worth target progress" value={metrics.progress} max={100} /><p>{metrics.progress.toFixed(1)}% of {lkr(goal.target)}{netWorth < 0 ? ` · ${lkr(-netWorth)} to reach zero net worth` : ""}</p><p>{metrics.wealthMonths === 0 ? "Your recorded net worth meets this target." : metrics.wealthMonths === null ? "Set monthly net-worth growth to model your timeline." : `About ${metrics.wealthMonths} months at ${lkr(goal.monthlyWealth)} monthly net-worth growth.`}</p></article></div>
    <div className="analytics-position"><span>Recorded assets <b>{lkr(assets)}</b></span><span>Customer receivables <b>{lkr(Number(receivables[0]?.amount??0))}</b></span><span>Loans & cards <b>{lkr(debt)}</b></span><span>Unpaid bills <b>{lkr(unpaid)}</b></span><span>Net worth <b>{lkr(netWorth)}</b></span></div>
    <form action="/api/goals" method="post" className="analytics-goal-form"><label>Wealth target (LKR)<input type="number" name="target" min="0.01" max="999999999999" step="0.01" defaultValue={goal.target} required /></label><label>Monthly debt repayment (LKR)<input type="number" name="monthlyDebt" min="0" max="999999999999" step="0.01" defaultValue={goal.monthlyDebt} required /></label><label>Monthly net-worth growth (LKR)<input type="number" name="monthlyWealth" min="0" max="999999999999" step="0.01" defaultValue={goal.monthlyWealth} required /></label><button className="button primary" type="submit">Save targets</button></form>
    <p className="analytics-note">Timelines are separate constant-amount scenarios, not forecasts or sequential milestones. They assume no interest, investment returns, fees, new borrowing or other changes. Paying principal from existing cash reduces cash and debt equally, so it does not itself increase net worth. Net worth includes only assets and obligations recorded in this app; add missing balances before relying on this measure.</p></section>
    </main></>;
}


