CREATE TABLE FamilyLoan (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  lender ENUM('ME','WIFE') NOT NULL,
  borrower ENUM('ME','WIFE') NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  repaidAmount DECIMAL(15,2) NOT NULL DEFAULT 0,
  loanDate DATE NOT NULL,
  description VARCHAR(300) NULL,
  status ENUM('OPEN','PARTIALLY_PAID','PAID','VOID') NOT NULL DEFAULT 'OPEN',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX FamilyLoan_lender_status_idx (lender,status),
  INDEX FamilyLoan_borrower_status_idx (borrower,status)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE FinancialTransaction MODIFY COLUMN type ENUM('INCOME','EXPENSE','TRANSFER','ACCRUED_EXPENSE','DEBT_PAYMENT','OPENING_BALANCE','ADJUSTMENT','PARTY_PAYMENT','FAMILY_LOAN_ADVANCE','FAMILY_LOAN_REPAYMENT') NOT NULL;
ALTER TABLE FinancialTransaction ADD COLUMN familyLoanId VARCHAR(191) NULL, ADD INDEX FinancialTransaction_familyLoanId_idx (familyLoanId), ADD CONSTRAINT FinancialTransaction_familyLoanId_fkey FOREIGN KEY (familyLoanId) REFERENCES FamilyLoan(id) ON DELETE RESTRICT;
