import Link from "next/link";
import { Nav } from "@/components/nav";
import { requireSession } from "@/lib/auth";
import { rows } from "@/lib/db";
import { UNITS } from "@/lib/expenses";
export const dynamic="force-dynamic";
export default async function Items({searchParams}:{searchParams:Promise<{q?:string;error?:string;saved?:string}>}) {
  await requireSession(); const params=await searchParams;
  const [items,categories]=await Promise.all([rows<any>("SELECT i.*,c.name category FROM Item i JOIN Category c ON c.id=i.categoryId WHERE i.name LIKE ? ORDER BY i.isActive DESC,i.name",[`%${params.q||""}%`]),rows<any>("SELECT id,name FROM Category WHERE kind='EXPENSE' AND isActive=1 ORDER BY name")]);
  function form(item?:any){return <form action="/api/items" method="post" className="form-grid"><input type="hidden" name="id" value={item?.id||""}/><label>Item name<input name="name" defaultValue={item?.name} maxLength={140} required/></label><label>Expense category<select name="categoryId" defaultValue={item?.categoryId} required>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Default unit (optional)<select name="defaultUnit" defaultValue={item?.defaultUnit||""}><option value="">No default unit</option>{UNITS.map(u=><option key={u}>{u}</option>)}</select></label><label className="check"><input name="isActive" type="checkbox" defaultChecked={item?Boolean(item.isActive):true}/>Active</label><button className="button primary">{item?"Save item":"Create item"}</button></form>}
  return <><Nav/><main><div className="page-heading"><div><h1>Item Master</h1><p className="muted">New items are also created automatically when you save an expense. Category and unit changes apply to future entries; past quantities and categories stay intact.</p></div><Link href="/master-data?section=CATEGORY" className="button">Expense categories</Link></div>{params.error&&<p role="alert">Unable to save. Check the category and name; an item with that name may already exist in this category.</p>}{params.saved&&<p role="status">Item saved.</p>}<section className="panel"><details><summary>Add an item</summary>{categories.length?form():<p>Create an expense category first.</p>}</details></section><section className="panel"><form className="report-picker"><label>Search items<input name="q" defaultValue={params.q}/></label><button className="button">Search</button></form>{items.map(item=><details className="item-master-row" key={item.id}><summary><strong>{item.name}</strong> · {item.category} · {item.defaultUnit||"No default unit"} · {item.isActive?"Active":"Inactive"}</summary>{form(item)}</details>)}{!items.length&&<p>No items yet. Add an expense with an item name to start tracking purchases.</p>}</section></main></>;
}
