CREATE TABLE Receivable (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  owner ENUM('ME','WIFE') NOT NULL DEFAULT 'ME',
  debtor VARCHAR(140) NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  receivedAmount DECIMAL(15,2) NOT NULL DEFAULT 0,
  receivableDate DATE NOT NULL,
  description VARCHAR(300) NULL,
  status ENUM('OPEN','PARTIALLY_PAID','PAID','VOID') NOT NULL DEFAULT 'OPEN',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  INDEX Receivable_owner_status_idx (owner,status)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
ALTER TABLE FinancialTransaction MODIFY COLUMN type ENUM('INCOME','EXPENSE','TRANSFER','ACCRUED_EXPENSE','DEBT_PAYMENT','OPENING_BALANCE','ADJUSTMENT','PARTY_PAYMENT','FAMILY_LOAN_ADVANCE','FAMILY_LOAN_REPAYMENT','RECEIVABLE_ADVANCE','RECEIVABLE_COLLECTION') NOT NULL;
ALTER TABLE FinancialTransaction ADD COLUMN receivableId VARCHAR(191) NULL, ADD INDEX FinancialTransaction_receivableId_idx (receivableId), ADD CONSTRAINT FinancialTransaction_receivableId_fkey FOREIGN KEY (receivableId) REFERENCES Receivable(id) ON DELETE RESTRICT;
