import crypto from "node:crypto";
import { z } from "zod";
import { currentOwner, relativeRedirect } from "@/lib/auth";
import { requireApiSession } from "@/lib/route-auth";
import { transaction } from "@/lib/db";
import { validDate } from "@/lib/analytics";
const schema=z.object({receivableId:z.string().uuid(),accountId:z.string().min(1).max(191),amount:z.coerce.number().positive().max(999999999).refine(n=>Math.round(n*100)===n*100),transactionDate:z.string().refine(validDate),description:z.string().max(300).optional()});
class InputError extends Error {}
export async function POST(request:Request){const denied=await requireApiSession();if(denied)return denied;const owner=await currentOwner(),parsed=schema.safeParse(Object.fromEntries((await request.formData()).entries()));if(!parsed.success)return relativeRedirect("/receivables?error=1");const d=parsed.data;try{await transaction(async c=>{const find=async(sql:string,v:unknown[]) => (await c.execute<any[]>(sql,v))[0][0],receivable=await find("SELECT * FROM Receivable WHERE id=? FOR UPDATE",[d.receivableId]),account=await find("SELECT id,owner,type FROM Account WHERE id=? AND isActive=1 FOR UPDATE",[d.accountId]);if(!receivable||receivable.owner!==owner||receivable.status==="PAID"||!account||account.owner!==owner||!["CASH","BANK","SAVINGS"].includes(account.type)||Number(receivable.amount)-Number(receivable.receivedAmount)<d.amount)throw new InputError();const received=Number(receivable.receivedAmount)+d.amount,status=received===Number(receivable.amount)?"PAID":"PARTIALLY_PAID",tx=crypto.randomUUID();await c.execute("UPDATE Receivable SET receivedAmount=?,status=?,updatedAt=NOW(3) WHERE id=?",[received,status,d.receivableId]);await c.execute("INSERT INTO FinancialTransaction (id,type,status,amount,transactionDate,description,scope,owner,accountId,receivableId,updatedAt) VALUES (?,'RECEIVABLE_COLLECTION','POSTED',?,?,?,'PERSONAL',?,?,?,NOW(3))",[tx,d.amount,d.transactionDate,d.description||null,owner,d.accountId,d.receivableId]);await c.execute("INSERT INTO AccountEntry (id,accountId,transactionId,amount,entryDate) VALUES (?,?,?,?,?)",[crypto.randomUUID(),d.accountId,tx,d.amount,d.transactionDate]);});}catch(error){if(error instanceof InputError)return relativeRedirect("/receivables?error=1");throw error;}return relativeRedirect("/receivables?collected=1");}
